name: Release to PyPI
on:
  push:
    tags: ["*"]
jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install dependencies
        run: pip install -r requirements/build-requirements.txt
      - name: Build package
        run: hatch build
      - name: Publish distribution 📦 to PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@v1.12.3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install the project
        run: uv sync --all-groups
      - name: Build wheel
        run: uv build
      - name: Publish package
        run: uv publish
