name: Release to PyPI
on:
  push:
    tags: ["*"]
jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install the project
        run: uv sync --all-groups
      - name: Build wheel
        run: uv build
      - name: Publish package
        run: uv publish
