name: Test publish to TestPyPI
on:
  workflow_dispatch:
    inputs:
      version_suffix:
        description: 'Version suffix (e.g., rc1, beta1, dev1)'
        required: false
        default: 'dev1'
jobs:
  test-publish:
    runs-on: ubuntu-latest
    environment: testpypi
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Generate test version
        id: version
        run: |
          BASE_VERSION=$(grep '^version = ' pyproject.toml | cut -d'"' -f2)
          SUFFIX="${{ github.event.inputs.version_suffix }}"
          TEST_VERSION="${BASE_VERSION}.${SUFFIX}"
          echo "version=${TEST_VERSION}" >> $GITHUB_OUTPUT
          echo "Generated test version: ${TEST_VERSION}"
      - name: Update version for testing
        run: |
          sed -i 's/^version = .*/version = "${{ steps.version.outputs.version }}"/' pyproject.toml
      - name: Build wheel
        run: uv build
      - name: Publish to TestPyPI
        run: uv publish --index testpypi